-- Expand the active product catalog so the site can show the additional
-- requested commodities together with live KAMIS price data.

merge into public.products as target
using (
  values
  (
    '55555555-5555-4555-8555-555555555555',
    '쌀',
    '식량작물',
    '100',
    '111',
    '00',
    '04',
    '20kg',
    true,
    50,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"백미/현미는 추후 품종과 등급을 분리 검증한다."}'::jsonb
  ),
  (
    '66666666-6666-4666-8666-666666666666',
    '고구마',
    '식량작물',
    '100',
    '151',
    '00',
    '04',
    '1kg',
    true,
    60,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"verified_product_info":"itemcode 151, kindcode 밤, retail rank 상품","notes":"고구마는 밤 품종 기준으로 우선 노출한다."}'::jsonb
  ),
  (
    '77777777-7777-4777-8777-777777777777',
    '감자',
    '식량작물',
    '100',
    '152',
    '00',
    '04',
    '100g',
    true,
    70,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"감자 품종과 단위는 productInfo 확인 후 조정한다."}'::jsonb
  ),
  (
    '88888888-8888-4888-8888-888888888888',
    '양배추',
    '채소류',
    '200',
    '212',
    '00',
    '04',
    '1포기',
    true,
    80,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"양배추는 단위와 품종을 추가 확인한다."}'::jsonb
  ),
  (
    '99999999-9999-4999-8999-999999999999',
    '시금치',
    '채소류',
    '200',
    '213',
    '00',
    '04',
    '100g',
    true,
    90,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"시금치는 조사 단위와 품종을 추가 확인한다."}'::jsonb
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    '당근',
    '채소류',
    '200',
    '216',
    '00',
    '04',
    '1kg',
    true,
    100,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"당근은 국산/수입 구분이 필요하다."}'::jsonb
  ),
  (
    'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    '마늘',
    '채소류',
    '200',
    '217',
    '00',
    '04',
    '1kg',
    true,
    110,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"피마늘/깐마늘 계열은 품종 코드 재확인이 필요하다."}'::jsonb
  ),
  (
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    '양파',
    '채소류',
    '200',
    '245',
    '00',
    '04',
    '1kg',
    true,
    120,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"양파는 국산 품목 기준으로 우선 노출한다."}'::jsonb
  ),
  (
    'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
    '생강',
    '채소류',
    '200',
    '220',
    '00',
    '04',
    '100g',
    true,
    130,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"생강은 국산/수입 구분을 추가 확인한다."}'::jsonb
  ),
  (
    'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',
    '호박',
    '채소류',
    '200',
    '222',
    '00',
    '04',
    '1개',
    true,
    140,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"호박은 애호박/단호박 분리 여부를 확인한다."}'::jsonb
  ),
  (
    'abababab-abab-4aba-8aba-abababababab',
    '토마토',
    '채소류',
    '200',
    '225',
    '00',
    '04',
    '1kg',
    true,
    150,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"verified_product_info":"itemcode 225, retail rank 상품","notes":"토마토는 품종이 단일 계열이라 우선 반영이 쉽다."}'::jsonb
  ),
  (
    'acacacac-acac-4aca-8aca-acacacacacac',
    '딸기',
    '과일류',
    '400',
    '226',
    '00',
    '04',
    '100g',
    true,
    160,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"딸기는 시즌 변동이 커서 최근 30일 흐름 확인용으로 유용하다."}'::jsonb
  ),
  (
    'adadadad-adad-4ada-8ada-adadadadadad',
    '사과',
    '과일류',
    '400',
    '411',
    '00',
    '04',
    '10개',
    true,
    170,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"사과는 후지 계열 기준으로 추후 품종 확장 가능."}'::jsonb
  ),
  (
    'aeaeaeae-aeae-4aea-8aea-aeaeaeaeaeae',
    '배',
    '과일류',
    '400',
    '412',
    '00',
    '04',
    '10개',
    true,
    180,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"배는 신고 품종 중심으로 우선 반영한다."}'::jsonb
  ),
  (
    'bcbcbcbc-bcbc-4bcb-8bcb-bcbcbcbcbcbc',
    '복숭아',
    '과일류',
    '400',
    '413',
    '00',
    '04',
    '10개',
    true,
    190,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"복숭아는 백도 중심으로 품종 세분화가 가능하다."}'::jsonb
  ),
  (
    'cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd',
    '포도',
    '과일류',
    '400',
    '418',
    '00',
    '04',
    '1kg',
    true,
    200,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"verified_product_info":"itemcode 418, fruit category candidate","notes":"포도는 캠벨/거봉/샤인머스켓으로 확장 가능."}'::jsonb
  ),
  (
    'dededede-dede-4ded-8ded-dededededede',
    '감귤',
    '과일류',
    '400',
    '422',
    '00',
    '04',
    '10개',
    true,
    210,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"verified_product_info":"itemcode 422, fruit category candidate","notes":"감귤은 노지/시설로 후속 구분 가능."}'::jsonb
  ),
  (
    'efefefef-efef-4efe-8efe-efefefefefef',
    '오렌지',
    '과일류',
    '400',
    '423',
    '00',
    '04',
    '1개',
    true,
    220,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"오렌지는 네이블 중심으로 우선 표시한다."}'::jsonb
  ),
  (
    'a1a1a1a1-a1a1-4a1a-8a1a-a1a1a1a1a1a1',
    '바나나',
    '과일류',
    '400',
    '427',
    '00',
    '04',
    '1개',
    true,
    230,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"바나나는 수입 품목으로 표시한다."}'::jsonb
  ),
  (
    'b1b1b1b1-b1b1-4b1b-8b1b-b1b1b1b1b1b1',
    '참외',
    '과일류',
    '400',
    '219',
    '00',
    '04',
    '10개',
    true,
    240,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"참외는 10개 단위로 우선 표시한다."}'::jsonb
  ),
  (
    'c1c1c1c1-c1c1-4c1c-8c1c-c1c1c1c1c1c1',
    '수박',
    '과일류',
    '400',
    '221',
    '00',
    '04',
    '1개',
    true,
    250,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"verified_product_info":"itemcode 221, fruit category candidate","notes":"수박은 1개 단위로 표시한다."}'::jsonb
  ),
  (
    'd1d1d1d1-d1d1-4d1d-8d1d-d1d1d1d1d1d1',
    '레몬',
    '과일류',
    '400',
    '424',
    '00',
    '04',
    '1개',
    true,
    260,
    '{"data_mode":"real_candidate","initial_candidate":true,"default_county_codes":["3613","3611"],"mock_supported":true,"notes":"레몬은 수입 품목으로 우선 표시한다."}'::jsonb
  )
) as source (
  id,
  display_name,
  category_name,
  kamis_category_code,
  kamis_item_code,
  kamis_kind_code,
  kamis_rank_code,
  default_unit,
  is_active,
  sort_order,
  metadata
)
on coalesce(target.kamis_item_code, '') = coalesce(source.kamis_item_code, '')
  and coalesce(target.kamis_kind_code, '') = coalesce(source.kamis_kind_code, '')
  and coalesce(target.kamis_rank_code, '') = coalesce(source.kamis_rank_code, '')
when matched then update set
  display_name = source.display_name,
  category_name = source.category_name,
  kamis_category_code = source.kamis_category_code,
  default_unit = source.default_unit,
  is_active = source.is_active,
  sort_order = source.sort_order,
  metadata = source.metadata,
  updated_at = now()
when not matched then insert (
  id,
  display_name,
  category_name,
  kamis_category_code,
  kamis_item_code,
  kamis_kind_code,
  kamis_rank_code,
  default_unit,
  is_active,
  sort_order,
  metadata
) values (
  source.id::uuid,
  source.display_name,
  source.category_name,
  source.kamis_category_code,
  source.kamis_item_code,
  source.kamis_kind_code,
  source.kamis_rank_code,
  source.default_unit,
  source.is_active,
  source.sort_order,
  source.metadata
);
